### ISSUE TITLE
Change migration name

### ISSUE THREAD

**Issue by ilbassa** [luyadev/luya-module-estore#3]
I think could be  useful change migration name from m170515_115236_basetables to m170515_115236_estore_basetables so it can be identified more precisely on migration table

**Comment by nadar** [comment]
Yes, what you are saying is true. But we should not changed the migration name afterwards as someone cloud have already installed this migration. If i rename the migration and someone runs migration again, it will try to apply to migration and which will fail. 

So i think its a good point for the next migration file but we can not change this one.

Thank you for the input.
