### ISSUE TITLE
Can not edit "Article Price" (error 404)

### ISSUE THREAD

**Issue by Webkadabra** [luyadev/luya-module-estore#4]
Problem can be fixed if I change ArticlePrice::ngRestAttributeTypes() from:
```
return [
            'article_id' => ['selectModel', 'modelClass' => Article::class],
            'currency_id' => ['selectModel', 'modelClass' => Currency::class],
            'qty' => 'number',
            'price' => 'decimal',
        ];
```

To:
```
        return [
            'article_id' => 'number',
            'currency_id' => 'number',
            'qty' => 'number',
            'price' => 'decimal',
        ];
```

**Comment by Webkadabra** [comment]
Looks like in my admin CRUD for admin of articles prices, application uses actual article name and actual currency name to build a REST api endpoint, and it result's in 404. For example:

http://luya.test/admin/api-estore-articleprice/1%201%20%D0%9A%D0%BE%D0%BA%D0%BE%D1%81%D0%BE%D0%B2%D0%BE%D0%B5%20%D0%BC%D0%B0%D1%81%D0%BB%D0%BE%201%20Ekoliya%20%D0%9A%D0%BE%D0%BA%D0%BE%D1%81%D0%BE%D0%B2%D0%BE%D0%B5%20%D0%BC%D0%B0%D1%81%D0%BB%D0%BE%20450%20%D0%BC%D0%BB%20CCOIL%20100,2%200%20USD%2027,1?ngrestCallType=update&fields=article_id%2Ccurrency_id%2Cqty%2Cprice

**Comment by nadar** [comment]
So the admin product overview does not work? Or are you accessing via API?

**Comment by Webkadabra** [comment]
All pages do work except "Edit Article Price". I can even create article price, but I can't edit it, because LUYA makes a weird endpoint to update API, see:
`http://luya.test/admin/api-estore-articleprice/1 1 Coconut Oil 1 ProducerName SKU,2 0 USD 27,1?ngrestCallType=update&fields=article_id%2Ccurrency_id%2Cqty%2Cprice`

**Comment by Webkadabra** [comment]
I mean I understand that this part `1 1 Coconut Oil 1 ProducerName SKU,2 0 USD 27,1` really should be `1,1,2` - `1` for Article ID, `1` for QTY and `2` for Currency ID, because ArticlePrice has a composite PrimaryKey.

**Comment by nadar** [comment]
Ok i will take a quick look on this asap.

**Comment by Webkadabra** [comment]
@nadar appreciate it! I get what the issue is I'm just not as good in LUYA code to pin-point where it goes wrong.

**Comment by nadar** [comment]
the module is still work in progress anyhow, so things will change in future.

**Comment by nadar** [comment]
I can confirm the bug. thanks

**Comment by nadar** [comment]
I just pushed a commit in order to fix this, and also the strict di injection. Make sure to use latest dev-master of admin, otherwise you will get an error. let me know if it works.

**Comment by Webkadabra** [comment]
@nadar Thanks, it works well now, and I've learned something about LUYA :+1:
