### ISSUE TITLE
Product to article relation

### ISSUE THREAD

**Issue by boehsermoe** [luyadev/luya-module-estore#7]
Actually a product have no attributes (only a attribute set). When I call a product like `$product = Product::findone(1)` it is not possible to display the product description. Because only the article has a `article_attribute_value`.
I think the article table is obsolete and instead the concret article should be in the product table. And for the relation to the parent product there is a new table needed also for the stock quantity.

The new db schema could be:

{product}      <-     {product_attribute_value}
{product}      <-     {product_stock_status}
{product}      <-     {product_link}

**Comment by siripravi** [comment]
Can we use this model?
![LuyaEstore](https://github.com/luyadev/luya-module-estore/assets/174201/f1d217ca-046e-4a71-ae7d-a683ca160d08)

**Comment by nadar** [comment]
wo do not further develop this module - you can fork it and do whatever you like 👍
